apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kalygo-embeddings-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/kalygo-436411/kalygo-embeddings-api/kalygo-embeddings-api
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: POSTGRES_URL
                  key: latest
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: AUTH_SECRET_KEY
                  key: latest
            - name: AUTH_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: AUTH_ALGORITHM
                  key: latest
          ports:
            - containerPort: 8080